### ISSUE TITLE
Create a new "student" entry to the participant list.

### ISSUE THREAD

**Issue by GMELIOT** [codebar/pairing-tool#12]
As an organiser I want to be able to add a new student to the list so that if the student didn't sign up they can still be added to the pairing process.

**Comment by jmbriano** [comment]
@Klarala13 what are the next steps for this taks?
I see the issue is "closed" but at the same time I found it in "To refine" column. 

If there is work left, it should not be closed yet. If we keep it it "to Refine" it means that we need a better task definition. In this case I would live it there as but in open status (not closed)

**Comment by Klarala13** [comment]
I would say it is not finished yet, because I am still working on a local
storage and the data doesn't persist yet.
However, I think that day it was good to close it so everyone could pull
and be able to work on the same structure.
I agree that we shouldn't close them until completely finished, but I think
in this case, it made sense for all of us to have access to it ;)
I think that's one of the things we need to discuss: how the workflow will
go (testing from the start? Require one review to close the request? Can we
all post tasks on the board or should we discuss them first? Etc).
Maybe on Thursday we can decide some of them ;)

**Comment by hassnian** [comment]
Yes we can talk this Thursday, regarding the development of the app could you explain why are you using localstorage , if we use localstarage we will not be able to have the list on more than one computer.

**Comment by Klarala13** [comment]
Well, for now, we don't have a DB or anything I can post the students data
to. I find it useful for now. If we don't want to use it, I can take it out
before merging.
